version: '3.8'

services:
  getway:
    build:
      context: ./getway
      dockerfile: Dockerfile

    container_name: getway
    ports:
      - "8000:8000"

    environment:
      - APP_HOST=0.0.0.0
      - APP_PORT=8000
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4317
      - OTEL_SERVICE_NAME=api-gateway
      - SERVICE_VERSION=1.0.0
      - ENVIRONMENT=development
      - PYTHONUNBUFFERED=1

    restart: always

    depends_on:
      - user-service

    networks:
      - coffee-shop

  user-service:
    build:
      context: ./authService
      dockerfile: Dockerfile

    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=jaeger:4317
      - OTEL_SERVICE_NAME=user-service

    container_name: authService

    restart: always

    depends_on:
      - postgres-user-service

    networks:
      - coffee-shop


  postgres-user-service:
    image: postgres:15-alpine
    container_name: user-service-db

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: users_db

    ports:
      - "5433:5432"

    volumes:
      - ./authService/migrations:/docker-entrypoint-initdb.d

    restart: unless-stopped

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d users_db" ]
      interval: 10s
      timeout: 5s
      retries: 5

    networks:
      - coffee-shop

  order-service:
    build:
      context: ./orderService
      dockerfile: Dockerfile

    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=jaeger:4317
      - OTEL_SERVICE_NAME=order-service

    container_name: orderService

    restart: always

    depends_on:
      - postgres-order-service

    networks:
      - coffee-shop

  postgres-order-service:
    image: postgres:15-alpine
    container_name: order-service-db

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: orders_db

    ports:
      - "5434:5432"

    volumes:
      - ./orderService/migrations:/docker-entrypoint-initdb.d

    restart: unless-stopped

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d orders_db" ]
      interval: 10s
      timeout: 5s
      retries: 5

    networks:
      - coffee-shop

  inventory-service:
    build:
      context: ./inventoryService
      dockerfile: Dockerfile

    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=jaeger:4317
      - OTEL_SERVICE_NAME=inventory-service

    container_name: inventoryService

    restart: always

    depends_on:
      - postgres-inventory-service

    networks:
      - coffee-shop

  postgres-inventory-service:
    image: postgres:15-alpine
    container_name: inventory-service-db

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: inventory_db

    ports:
      - "5435:5432"

    volumes:
      - ./inventoryService/migrations:/docker-entrypoint-initdb.d

    restart: unless-stopped

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d inventory_db" ]
      interval: 10s
      timeout: 5s
      retries: 5

    networks:
      - coffee-shop

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "16686:16686" # Веб-интерфейс Jaeger UI
      - "4317:4317"   # Порт для приема трасс по OTLP gRPC
      - "4318:4318"   # Порт для приема трасс по OTLP HTTP
    networks:
      - coffee-shop

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false  # Отключаем безопасность для local dev
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    networks:
      - coffee-shop

  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.0
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - coffee-shop

  filebeat:
    image: docker.elastic.co/beats/filebeat:8.11.0
    container_name: filebeat
    user: root
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command: [ "--strict.perms=false" ]
    depends_on:
      - elasticsearch
      - kibana
    networks:
      - coffee-shop


networks:
  coffee-shop:
    driver: bridge