version: '3.8'

services:
  getway:
    build:
      context: ./getway
      dockerfile: Dockerfile

    container_name: getway
    ports:
      - "8000:8000"

    environment:
      - APP_HOST=0.0.0.0
      - APP_PORT=8000

    restart: always
